version: "3.9"
   
services:
  db:
    image: postgres
    volumes:
      - ./DjangoApp/data/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "6543:5432"
  web:
    build: 
      context: ./DjangoApp
      dockerfile: Dockerfile.dev
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./DjangoApp:/code
    ports:
      - "8000:8000"
    depends_on:
      - db
